spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: YDDtvwoP3y0CXZIgYHg_
            client-secret: YTV8OWGlll
            redirect_uri_template: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization_grant_type: authorization_code
            scope:
              - name
              - emaiL
              - profile_image
            client-name: Naver
        # provider
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

  datasource:
    url:  jdbc:sqlserver://210.103.143.194:19;database=DEV_APP
    username: sa
    password: 119aselcni!.@1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false  #ID값을 테이블별 부여...
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
server:
  port: 9090